chessanno/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("games/", include("games.urls", namespace="games")),
    path('admin/', admin.site.urls),
]

games/urls.py
from django.urls import path
from .views import GameDetail, GameList, create_analysis, create_comment

app_name='games'

urlpatterns = [
    path("<int:pk>/<int:ply>/", GameDetail.as_view(), name="detail"),
    path("<int:pk>/", GameDetail.as_view(), name="detail"),
    path("<int:pk>/analyze", create_analysis, name="analyze"),
    path("<int:pk>/<int:ply>/comment", create_comment, name="comment"),
    path("", GameList.as_view(), name="list"),
]

events/models.py
from django.db import models

# Create your models here.
class ChessEvent(models.Model):
    name = models.TextField(blank=True, null=True, help_text="Name of the tournament or match event")
    site = models.CharField(max_length=64, blank=True, null=True, help_text="Location of the event. City, Region, COUNTRY")

    def __str__(self):
        return self.name

class ChessRound(models.Model):
    event = models.ForeignKey(ChessEvent, on_delete=models.CASCADE)
    num = models.IntegerField(blank=True, null=True, help_text="Playing round ordinal of the game within the event")

    def __str__(self):
        return f"{self.event.name} R{self.num}"

games/models.py
import io
import chess.pgn
from django.db import models
from events.models import ChessEvent, ChessRound
from players.models import ChessPlayer
from parse.state import pgn_to_game

class ChessGame(models.Model):
    event = models.ForeignKey(ChessEvent, on_delete=models.SET_NULL, blank=True, null=True, help_text="The tournament or match event")
    round = models.ForeignKey(ChessRound, on_delete=models.SET_NULL, blank=True, null=True, help_text="The round of the tournament")
    date = models.DateField(blank=True, null=True, help_text="Starting date of the game")
    white = models.ForeignKey(ChessPlayer, on_delete=models.CASCADE, help_text="Player of the white pieces", related_name='white_games')
    white_elo = models.IntegerField(blank=True, null=True)
    black = models.ForeignKey(ChessPlayer, on_delete=models.CASCADE, help_text="Player of the black pieces", related_name='black_games')
    black_elo = models.IntegerField(blank=True, null=True)
    winner = models.ForeignKey(ChessPlayer, blank=True, null=True, on_delete=models.CASCADE, help_text="Winner of the game; None for draw")
    hashcode = models.CharField(max_length=8, help_text="A hash code of the moves in the game")
    total_ply_count = models.IntegerField()
    imported_pgn = models.TextField(help_text="The imported PGN of the game")
    processed_pgn = models.TextField(blank=True, null=True, help_text="The PGN after the annotator has visited it")

    def __str__(self):
        return self.hashcode

    @property
    def game(self) -> chess.pgn.Game:
        if self.processed_pgn is not None:
            pgn = chess.pgn.read_game(io.StringIO(self.processed_pgn))    
        else:
            pgn = chess.pgn.read_game(io.StringIO(self.imported_pgn))
        
        if pgn is None:
            raise Exception("Error reading pgn string")
        return pgn
    
    @property
    def result(self) -> str:
        if not self.winner:
            return "1/2 - 1/2"
        if self.winner == self.black:
            return "0-1"
        if self.winner == self.white:
            return "1-0"
        return "*"

    def at_ply(self, ply: int) -> chess.pgn.ChildNode:
        if ply > self.total_ply_count:
            raise Exception("This game has fewer plies than requested")

        game = self.game.variation(0)

        if game is None:
            raise Exception("Couldn't get main variation for game")
        
        for _ in range(1, ply):
            next_child = game.next()
            if next_child is not None:
                game = next_child

        return game

players/models.py
from typing import List
from django.db import models

# Create your models here.
class ChessPlayer(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, help_text="Romanicized name")
    
    def __str__(self):
        return self.name
        

games/forms.py
from django import forms

class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}),label="")

events/views.py
from django.shortcuts import render

# Create your views here.

games/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from django.urls import reverse
from django.views.generic import DetailView, ListView
from .models import ChessGame
from typing import Any, Dict
import chess, chess.pgn, chess.svg
from parse import analyze, state
from .forms import CommentForm
class GameDetail(DetailView):
    model = ChessGame

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        
        # UI
        context["nav"] = "games"

        # Traverse to correct ply
        current_ply = self.kwargs.get("ply", 1)
        context["current_ply"] = current_ply
        current_position: chess.pgn.ChildNode = self.object.at_ply(current_ply) # type: ignore

        # Describe the game for the template
        fish = current_position.eval()
        if fish is not None:
            context["eval"] = fish.pov(chess.WHITE).score(mate_score=100000) / 100

        if current_ply > 1:
            context["last_href"] = reverse("games:detail",kwargs={"pk": self.kwargs.get("pk"), "ply": current_ply - 1})
        if current_ply < self.object.total_ply_count: # type: ignore
            context["next_href"] = reverse("games:detail",kwargs={"pk": self.kwargs.get("pk"), "ply": current_ply + 1})

        check=None
        lastmove=None

        context["last_move"] = current_position.move
        
        if current_position.board().is_check():
            check=current_position.move.to_square
        else:
            lastmove=current_position.move

        context["comment"] = state.get_comment(current_position)
        context["comment_form"] = CommentForm(initial={"comment": context["comment"]})
        context["variations"] = current_position.variations
        context["svg"] = chess.svg.board(current_position.board(), lastmove=lastmove, check=check)
    
        return context

class GameList(ListView):
    model = ChessGame

def create_analysis(request, pk, depth=10):
    try:
        obj = ChessGame.objects.get(pk=pk)
        game = obj.game
        for node in game.mainline():
            fish = analyze.fish(node.board().fen(), depth)
            node.set_eval(fish.get("score"), depth)
        
        obj.processed_pgn = state.game_to_pgn(game)
        obj.save()

    except Exception:
        raise Exception("Unspecified analysis error")

    
    return redirect("games:detail", pk)

def create_comment(request: HttpRequest, pk: int, ply: int):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            obj = ChessGame.objects.get(pk=pk)
            game = obj.at_ply(ply)
            game = state.set_comment(game, request.POST.get("comment", ""))
            obj.processed_pgn = state.game_to_pgn(game.game())
            obj.save()
    else:
        obj = ChessGame.objects.get(pk=pk)
        game = obj.at_ply(ply)
        existing_comment = state.get_comment(game)
        form = CommentForm(initial={"comment": existing_comment})
    return redirect("games:detail", pk, ply+1)
        

players/views.py
from django.shortcuts import render

# Create your views here.

games/templates/games/chessgame_detail.html
{% extends 'base.html' %}
{% block subsidebar %}
<div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 160px">
    <div class="d-flex flex-row justify-content-between">
        <span class="fs-4">
            <a href="{% url 'games:detail' chessgame.pk %}" class="text-white">&larrb;</a>
        </span>
        <span class="fs-4">
            {% if last_href %}
                <a href="{{ last_href }}" class="text-white">&larr;</a>
            {% else %}
                &larr;
            {% endif %}
        </span>
        <span class="fs-4">
            {% if next_href %}
                <a href="{{ next_href }}" class="text-white">&rarr;</a>
            {% else %}
                &rarr;
            {% endif %}
        </span>
        <span class="fs-4">
            <a href="{% url 'games:detail' chessgame.pk chessgame.total_ply_count %}" class="text-white">&rarrb;</a>
        </span>
    </div>

    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            {% if variations|length > 1 %}
            <div class="dropdown-center d-grid gap-2">
                <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Variations
                </button>
                <ul class="dropdown-menu">
                    {% for variation in variations %}
                    <li><a class="dropdown-item text-center" href="#">{{ forloop.counter }}</a></li>
                    {% endfor %}
                </ul>
              </div>
            {% endif %}
        </li>
        <li class="nav-item">
            <span class="nav-link text-white">Move: {{ last_move }}</span>
        </li>
        <li class="nav-item">
            {% if eval %}
                <span class="nav-link text-white">Eval: {{ eval }}</span>
            {% else %}
                <a href="{% url 'games:analyze' chessgame.pk %}" class="nav-link bg-primary text-white">Analyze @35</a>
            {% endif %}
        </li>
    </ul>
    <div class="form-group">
        <form action="{% url 'games:comment' chessgame.pk current_ply %}" method="POST">
            {% csrf_token %}
            {{ comment_form }}
            <button type="submit" class="btn btn-primary btn-sm btn-block form-control">&check;</button>
        </form>
    </div>
</div>

{% endblock subsidebar %}
{% block title %}{{ chessgame }}{% endblock title %}
{% block subtitle %}{{ chessgame }}{% endblock subtitle %}
{% block content %}
    <span class="small text-center text-bg-dark">{{ chessgame.black }} {% if chessgame.black_elo %}({{ chessgame.black_elo }}) {% endif %}</span>
    {{ svg | safe }}
    <span class="small text-center text-bg-light">{{ chessgame.white }} {% if chessgame.white_elo %}({{ chessgame.white_elo }}) {% endif %}</span>
{% endblock content %}

games/templates/games/chessgame_list.html
{% extends 'base.html' %}
{% block title %}Game List{% endblock title %}
{% block content %}
    <div class="px-3">
    {% regroup chessgame_list by event as chessgame_event_list %}
        {% for event in chessgame_event_list %}
        <span class="fs-4"><span class="fw-bold">{{ event.grouper.name }}</span> ({{ event.grouper.site }})</span>
            <table class="table table-dark table-sm">
                <thead>
                    <th></th>
                    <th>Date</th>
                    <th>White</th>
                    <th>Black</th>
                    <th>Result</th>
                </thead>
                <tbody>
                    {% for game in event.list %}
                    <tr>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <a href="{% url 'games:detail' game.pk %}" class="btn btn-success"><i class="fa-solid fa-book"></i></a>
                                <a href="{% url 'games:analyze' game.pk %}" class="btn {% if game.processed_pgn %}btn-success{% else %}btn-secondary{% endif %}"><i class="fa-solid fa-magnifying-glass"></i></a>
                                <a href="" class="btn {% if game.video_url %}btn-success{% else %} btn-secondary{% endif %}"><i class="fa-solid fa-video"></i></a>
                                <a href="" class="btn btn-warning"><i class="fa-solid fa-x"></i></a>
                            </div>
                        </td>
                        <td>{{ game.date }}</td>
                        <td>{{ game.white }}</td>
                        <td>{{ game.black }}</td>
                        <td>{{ game.result }}</td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endfor %}
    </div>
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Untitled {% endblock title %} | Anno</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body class="text-bg-dark">
    <main class="d-flex flex-nowrap">
        <div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 140px">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                <span class="fs-4">{% block subtitle %} Anno {% endblock subtitle %}</span>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item">
                    <a href="#" class="nav-link text-white {% if nav == 'home' %}active{% endif %}" aria-current="page">
                        Home
                    </a>
                </li>
                <li>
                    <a href="#" class="nav-link text-white {% if nav == 'dashboard' %}active{% endif %}">
                        Dashboard
                    </a>
                </li>
                <li>
                    <a href="{% url 'games:list' %}" class="nav-link text-white {% if nav == 'games' %}active{% endif %}">
                        Games
                    </a>
                </li>
                {% block sidebar %}
                {% endblock sidebar %}
            </ul>
        </div>
        <div class="d-flex flex-column flex-grow-1 p-0 m-0 text-bg-primary vh-100">
            {% block content %}
            {% endblock content %}
        </div>
        {% block subsidebar %}
        {% endblock subsidebar %}

    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="{% static 'fontawesomefree/js/fontawesome.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/solid.js' %}"></script>

</body>

</html>